version: '3'

services:
  seeding-checker:
    build: .
    container_name: seeding-checker
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./output:/app/output
      - .:/app:ro
      - /vol3/1000/:/vol3/1000/:ro
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_FILE=/app/config/config.ini
      - PYTHONUNBUFFERED=1
    command: python app.py --config /app/config/config.ini
    user: "${UID:-1000}:${GID:-1000}" 