version: '3'

services:
  seeding-checker:
    image: eternalcurse/seeding-checker:latest
    container_name: seeding-checker
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./output:/app/output
      - /vol3/1000/:/vol3/1000/:ro
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_FILE=/app/config/config.ini
      - PYTHONUNBUFFERED=1
    user: "${UID:-1000}:${GID:-1000}" 